name: Publish Package
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1 
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run:  |
          npm ci
          npm rebuild node-sass
      - name: Tests
        run: npm run test
      - name: Test coverage
        run: npm run checkCoverage
      - name: Linting
        run: npm run lint
      - name: Security audit
        run: npm run npmAudit

  publish:
    name: publish module
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2.3.1 
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@your-github-username'
      - name: Install and build
        run: |
          npm install
          npm run buildCompiled
      - name: Reduce package.json file
        run: bash  utils/buildPackage.sh
      - name: Publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_PUBLISH }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_PUBLISH }}

  pages:
    name: publish gitHub pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout action
        uses: actions/checkout@v2.3.1 
        with:
          persist-credentials: false

      - name: Install and Build 
        run: npm run build

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: build 
          CLEAN: true 
